name = "art"
type = "javascript" # or "webpack", or "rust", depending on setup
compatibility_date = "2025-06-30"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format = "service-worker"